apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  namespace: keycloak
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Leave storageClassName empty to use your default (like nfs-subdir-external-provisioner)
  # Or explicitly define your storageClassName if required.